version: '3.8'

services:
  # El "ordenador" de la base de datos
  mongodb:
    image: mongo:latest
    container_name: konecto_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: konecto_backend
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb  # Espera a que la DB arranque
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: konecto_frontend
    ports:
      - "3000:80"  
    volumes:
      - ./client/src:/usr/share/nginx/html

volumes:
  mongo_data: # Para que no pierdas tus datos al apagar Docker